version: "3.3"
services:
  db:
    image: mysql
    working_dir: /db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    # command: sh -c '/db/wait-for-it.sh -t 0 localhost:3306'
    volumes:
    - ./db:/db