version: "3.3"
services:
  backend:
    image: ${BACKEND_IMAGE}
    working_dir: /app
    command: ${BACKEND_COMMAND}
    volumes:
      - ./backends/${BACKEND}/src:/app
  db:
    image: mysql
    working_dir: /db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    # command: sh -c '/db/wait-for-it.sh -t 0 localhost:3306'
    volumes:
    - ./db:/db