version: "3.3"
services:
  backend:
    image: python:3-alpine
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=index.py
    volumes:
      - ./backends/python-flask/app:/app
    ports:
      - "${PORT}:5000"