version: "3.3"
services:
  backend:
    image: imageName:version-alpine
    working_dir: /app
    command:  >
      sh -c "npm install &&
             npm start"
    volumes:
      - ./backends/<insert folder name>/app:/app
    ports:
      - "${PORT}:3000"