version: "3.3"
services:
  backend:
    image: node:15-alpine
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm start"
    volumes:
      - ./backends/node-express/app:/app
    ports:
      - "${PORT}:3000"